# ------------------------------------------------------------------------------
# IAM Development Environment
# ------------------------------------------------------------------------------

replicaCount: 1

image:
  repository: nikhilmhatre0317/shopsphere-user-service
  tag: dev
  pullPolicy: IfNotPresent

application:
  environment: development
  name: iam
  version: "1.0.0"
  host: 0.0.0.0
  port: 3000
  logLevel: debug

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

database:
  scheme: postgresql
  host: iam-postgres
  port: 5432
  name: iam
  username: postgres
  password: change-me
  connectTimeoutMs: 10000
  logQueries: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

probes:
  startup:
    path: /api/v1/health
    failureThreshold: 30
    periodSeconds: 10

  readiness:
    path: /api/v1/health
    initialDelaySeconds: 10
    periodSeconds: 10

  liveness:
    path: /api/v1/health
    initialDelaySeconds: 30
    periodSeconds: 20

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: false

ingress:
  enabled: false

nodeSelector: {}

affinity: {}

tolerations: []
