# environments/dev/user-service/user-db-values.yaml
replicaCount: 1

image:
  repository: postgres
  tag: "17.6"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 5432

database:
  name: user_db

auth:
  username: user_service
  password: user_service_password
  existingSecret: ""

storage:
  size: 5Gi
  storageClass: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  startup:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6

nodeSelector: {}

affinity: {}

tolerations: []

terminationGracePeriodSeconds: 60
