# ------------------------------------------------------------------------------
# Development Environment Overrides
# ------------------------------------------------------------------------------

replicaCount: 1

# ------------------------------------------------------------------------------
# Container Image
# ------------------------------------------------------------------------------
image:
  tag: "dev"
  pullPolicy: Always

# ------------------------------------------------------------------------------
# Application Configuration
# ------------------------------------------------------------------------------
config:
  nodeEnv: development
  logLevel: debug

# ------------------------------------------------------------------------------
# Database
# ------------------------------------------------------------------------------
database:
  host: user-db-postgres.shopsphere-infra.svc.cluster.local
  port: 5432
  name: user_db
  username: user_service
  password: user_service_password

  # Optional:
  # If specified, this value is used directly instead of constructing DATABASE_URL.
  # url: postgresql://user_service:user_service_password@user-db-postgres.shopsphere-infra.svc.cluster.local:5432/user_db

# ------------------------------------------------------------------------------
# Secrets
# ------------------------------------------------------------------------------
secret:
  create: true
  existingSecret: ""

  jwt:
    accessSecret: dev-access-secret
    refreshSecret: dev-refresh-secret

# ------------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------------
resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

# ------------------------------------------------------------------------------
# Health Checks
# ------------------------------------------------------------------------------
probes:

  startup:
    enabled: true

    initialDelaySeconds: 5

    periodSeconds: 5

    timeoutSeconds: 2

    failureThreshold: 30

  readiness:
    enabled: true

    initialDelaySeconds: 2

    periodSeconds: 10

    timeoutSeconds: 2

    failureThreshold: 3

    successThreshold: 1

  liveness:
    enabled: true

    initialDelaySeconds: 30

    periodSeconds: 30

    timeoutSeconds: 2

    failureThreshold: 3

# ------------------------------------------------------------------------------
# Scheduling
# ------------------------------------------------------------------------------
nodeSelector: {}

affinity: {}

tolerations: []
