{{- /*
------------------------------------------------------------------------------
IAM Service
------------------------------------------------------------------------------

This template creates a Kubernetes Service for the IAM application.

Why do we need a Service?

Pods are temporary.

Whenever a Pod is recreated because of:

- Application updates
- Node failures
- Pod crashes
- Kubernetes scheduling

its IP address changes.

Applications inside Kubernetes should NEVER communicate directly with a Pod.

Instead, they should always communicate through a Kubernetes Service.

Example:

User Service
      │
      ▼
http://iam:3000

Kubernetes automatically routes the request to a healthy IAM Pod.

------------------------------------------------------------------------------
*/ -}}

apiVersion: v1
kind: Service

metadata:
  # Service name.
  #
  # Example:
  #
  # iam
  #
  name: {{ include "iam.fullname" . }}

  labels:
    {{- include "iam.labels" . | nindent 4 }}

spec:

  # Kubernetes Service type.
  #
  # ClusterIP
  #   Internal communication only.
  #
  # NodePort
  #   Exposes the Service on every Kubernetes node.
  #
  # LoadBalancer
  #   Creates a cloud provider load balancer.
  #
  # For microservice-to-microservice communication,
  # ClusterIP is the recommended choice.
  #
  type: {{ .Values.service.type }}

  ports:

    - name: http

      # Port exposed by the Kubernetes Service.
      #
      port: {{ .Values.service.port }}

      # Port exposed by the application container.
      #
      targetPort: {{ .Values.application.port }}

      protocol: TCP

  # Select the IAM Pods.
  #
  # The selector labels must exactly match
  # the labels defined on the Deployment.
  #
  selector:
    {{- include "iam.selectorLabels" . | nindent 4 }}
