# ------------------------------------------------------------------------------
# Argo CD Application
# ------------------------------------------------------------------------------
#
# This Application deploys the users Helm chart into the
# development environment.
#
# Argo CD continuously monitors the GitOps repository.
#
# Whenever this file, the Helm chart, or the development values file
# changes, Argo CD synchronizes the Kubernetes cluster so that it
# matches the desired state stored in Git.
#
# ------------------------------------------------------------------------------
#
# Repository
#   ShopSphere-GitOps
#
# Helm Chart
#   charts/users
#
# Environment
#   Development
#
# Namespace
#   users
#
# Values File
#   dev/users/values.yaml
#
# ------------------------------------------------------------------------------

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  # Name displayed inside the Argo CD UI.
  #
  # Example:
  #
  # users-dev
  #
  name: users-dev

  # Namespace where Argo CD is installed.
  #
  namespace: argocd

spec:

  # Argo CD Project.
  #
  project: default

  # --------------------------------------------------------------------------
  # Source Repository
  # --------------------------------------------------------------------------

  source:

    # Git repository containing the Helm chart.
    #
    repoURL: https://github.com/Nikhil-Mhatre/shopsphere-gitops.git

    # Git branch to monitor.
    #
    targetRevision: main

    # Path to the Helm chart.
    #
    path: charts/users

    helm:

      # Environment-specific values file.
      #
      valueFiles:

        - ../../environments/development/users.yaml

      # Release Name
      releaseName: users

  # --------------------------------------------------------------------------
  # Destination Cluster
  # --------------------------------------------------------------------------

  destination:

    # Deploy to the in-cluster Kubernetes API.
    #
    server: https://kubernetes.default.svc

    # Kubernetes namespace.
    #
    namespace: users

  # --------------------------------------------------------------------------
  # Synchronization Policy
  # --------------------------------------------------------------------------

  syncPolicy:

    automated:

      # Remove Kubernetes resources that
      # no longer exist in Git.
      #
      prune: true

      # Restore resources if they are
      # modified manually.
      #
      selfHeal: true

    syncOptions:

      # Automatically create the namespace
      # if it does not exist.
      #
      - CreateNamespace=true
