{{- if not .Values.secret.existingSecret }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ include "user-service.fullname" . }}

  labels:
    {{- include "user-service.labels" . | nindent 4 }}

type: Opaque

stringData:

  JWT_ACCESS_SECRET: {{ .Values.secret.jwt.accessSecret | quote }}

  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.database.username .Values.database.password .Values.database.host .Values.database.port .Values.database.name | quote }}

  JWT_REFRESH_SECRET: {{ .Values.secret.jwt.refreshSecret | quote }}

{{- end }}
